"""
escalation.py
=============
The "longitudinal" half of the triage engine.

Given a chronologically ordered list of :class:`JournalEntry`, the escalation
detector inspects the last *N* entries and classifies the trajectory as
``Stable`` / ``Watch`` / ``Escalate``. Rules are intentionally simple and
transparent so they can be defended in the IEEE paper.

The module also produces a clinician-shareable Markdown export of the whole
session — used by the Streamlit "Clinician Report" page.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import List, Sequence

from constants import SEVERITY_RANK
from schemas import EscalationVerdict, JournalEntry

__all__ = [
    "detect_escalation",
    "export_session_markdown",
]

DEFAULT_WINDOW = 3


def _rank_to_label(rank: int) -> str:
    for label, value in SEVERITY_RANK.items():
        if value == rank:
            return label
    return "?"


def detect_escalation(
    entries: Sequence[JournalEntry],
    window: int = DEFAULT_WINDOW,
) -> EscalationVerdict:
    """
    Classify the recent trajectory.

    Rules (in priority order):

    1. **Escalate** — any Urgent entry in the window.
    2. **Escalate** — severity is strictly higher in the most recent entry
       than in the oldest entry in the window.
    3. **Watch** — at least two entries in the window are Moderate or above.
    4. **Stable** — otherwise.
    """
    if not entries:
        return EscalationVerdict("Stable", "No entries logged yet.", 0, 0)

    recent: List[JournalEntry] = list(entries[-window:])
    ranks = [SEVERITY_RANK[e.prediction.severity] for e in recent]
    delta = ranks[-1] - ranks[0]
    max_rank = max(ranks)

    if any(e.prediction.severity == "Urgent" for e in recent):
        return EscalationVerdict(
            "Escalate",
            "An Urgent severity entry was logged in the recent window — seek care now.",
            len(recent),
            delta,
        )

    if delta >= 1:
        return EscalationVerdict(
            "Escalate",
            f"Severity is trending upward ({_rank_to_label(ranks[0])} -> {_rank_to_label(ranks[-1])}).",
            len(recent),
            delta,
        )

    if max_rank >= 1 and len(recent) >= 2:
        return EscalationVerdict(
            "Watch",
            "Symptoms are persisting at a moderate level — monitor closely.",
            len(recent),
            delta,
        )

    return EscalationVerdict(
        "Stable",
        "Symptoms appear mild and not worsening.",
        len(recent),
        delta,
    )


# ---------------------------------------------------------------------------
# Markdown export
# ---------------------------------------------------------------------------

def _format_entry(index: int, entry: JournalEntry) -> List[str]:
    pred = entry.prediction
    lines = [
        f"### {index}. {entry.timestamp}",
        "",
        f"> {entry.user_text}",
        "",
        f"- **Predicted disease:** {pred.disease}  (conf. {pred.confidence:.2f})",
        f"- **Severity:** {pred.severity}  ({pred.severity_source})",
    ]
    if pred.red_flags_hit:
        lines.append(f"- **Red-flag phrases detected:** {', '.join(pred.red_flags_hit)}")
    diff = "; ".join(f"{d} ({c:.2f})" for d, c in pred.differential)
    lines.append(f"- **Differential top-3:** {diff}")
    if pred.drivers:
        lines.append(f"- **Top driver tokens:** {', '.join(t for t, _ in pred.drivers)}")
    lines.append("")
    return lines


def export_session_markdown(
    entries: Sequence[JournalEntry],
    escalation: EscalationVerdict,
) -> str:
    """Render a Markdown summary ready to paste into a teleconsult or email."""
    now = datetime.now(timezone.utc).isoformat()
    out: List[str] = [
        "# Symptom Triage Journal — Session Summary",
        "",
        f"_Generated: {now}_",
        "",
        f"**Triage verdict:** {escalation.level}",
        f"**Reason:** {escalation.reason}",
        "",
        "## Entries",
        "",
    ]
    for i, entry in enumerate(entries, start=1):
        out.extend(_format_entry(i, entry))
    out.extend(
        [
            "---",
            "_This report is generated by an AI prototype and is not a medical diagnosis._",
        ]
    )
    return "\n".join(out)
