"""
Clinician Report page — generates a Markdown summary of the session.

The user gets:

* a summary metrics strip,
* severity breakdown chips,
* the current escalation verdict,
* a preview of the Markdown report,
* one-click downloads as ``.md`` and ``.txt``.
"""

from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Sequence

# Make the parent app/ directory importable when Streamlit launches the page.
_APP_DIR = Path(__file__).resolve().parent.parent
if str(_APP_DIR) not in sys.path:
    sys.path.insert(0, str(_APP_DIR))

import streamlit as st

import ui
from constants import SEVERITY_COLOR, SEVERITY_LEVELS, SEVERITY_RANK
from escalation import export_session_markdown
from schemas import JournalEntry

st.set_page_config(page_title="Clinician Report", page_icon="📋", layout="wide")

st.title("📋 Clinician-Shareable Report")
st.caption(
    "Generates a structured summary of your session that you can paste into a "
    "teleconsult, an email, or print for your GP."
)

entries: Sequence[JournalEntry] = ui.require_journal(
    empty_message=(
        "No entries to export yet. Go to the **Live Triage** page and log at "
        "least one entry to your journal."
    ),
)

verdict = ui.current_escalation()
report = export_session_markdown(entries, verdict)


# ---------------------------------------------------------------------------
# Summary metrics
# ---------------------------------------------------------------------------

severities = [e.prediction.severity for e in entries]
peak_rank = max(SEVERITY_RANK[s] for s in severities)
peak_severity = next(level for level, rank in SEVERITY_RANK.items() if rank == peak_rank)
red_flag_count = sum(1 for e in entries if e.prediction.red_flags_hit)

m1, m2, m3, m4, m5 = st.columns(5)
m1.metric("Total entries", len(entries))
m2.metric("Triage verdict", verdict.level)
m3.metric("Severity delta", f"{verdict.delta_severity:+d}")
m4.metric("Peak severity", peak_severity)
m5.metric("Red-flag entries", red_flag_count)

st.markdown("**Severity breakdown:**")
chip_cols = st.columns(len(SEVERITY_LEVELS))
for col, level in zip(chip_cols, SEVERITY_LEVELS):
    with col:
        st.markdown(
            ui.severity_counter(level, severities.count(level)),
            unsafe_allow_html=True,
        )

st.divider()


# ---------------------------------------------------------------------------
# Escalation verdict + report preview
# ---------------------------------------------------------------------------

ui.render_escalation_banner(verdict, show_window=False)
st.divider()

st.markdown("### Report preview")
st.markdown(report)


# ---------------------------------------------------------------------------
# Downloads
# ---------------------------------------------------------------------------

st.divider()
st.markdown("### Download")

filename_stem = f"triage_report_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}"

col_a, col_b = st.columns(2)
with col_a:
    st.download_button(
        "⬇️ Download as Markdown (.md)",
        data=report,
        file_name=f"{filename_stem}.md",
        mime="text/markdown",
        use_container_width=True,
    )
with col_b:
    st.download_button(
        "⬇️ Download as plain text (.txt)",
        data=report,
        file_name=f"{filename_stem}.txt",
        mime="text/plain",
        use_container_width=True,
    )

st.caption(
    "⚠️ This report is generated by an AI prototype and does **not** constitute a "
    "medical diagnosis. Share it with a qualified clinician for interpretation."
)
